services:
  java:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: java-dev
    working_dir: /workspace

    volumes:
      - ./workspace:/workspace

    stdin_open: true
    tty: true

    ports:
      - "8081:8081"

    entrypoint:
      - /usr/local/bin/entrypoint.sh
